# Generated by Django 6.0.6 on 2026-06-05 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('location', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_number', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('national_id', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('farm_size_acres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('location', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('exited', 'Exited')], default='active', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('season_type', models.CharField(choices=[('main_crop', 'Main Crop'), ('fly_crop', 'Fly Crop')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'season_type'), name='unique_season_name_and_type'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='season_end_date_after_start_date')],
            },
        ),
        migrations.CreateModel(
            name='MillingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=40, unique=True)),
                ('cherry_in_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parchment_out_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('green_bean_out_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('milled_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milling_batches', to='core.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin / Manager'), ('field_officer', 'Field Officer'), ('member', 'Member')], default='member', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleProceed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.CharField(max_length=160)),
                ('sold_on', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_proceeds', to='core.season')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_kg__gt', 0)), name='sale_quantity_positive'), models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='sale_gross_amount_not_negative'), models.CheckConstraint(condition=models.Q(('expenses__gte', 0)), name='sale_expenses_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='core.member')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='core.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('member', 'season'), name='unique_member_season_payout'), models.CheckConstraint(condition=models.Q(('delivered_kg__gte', 0)), name='payout_delivered_kg_not_negative'), models.CheckConstraint(condition=models.Q(('gross_share__gte', 0)), name='payout_gross_share_not_negative'), models.CheckConstraint(condition=models.Q(('loan_deductions__gte', 0)), name='payout_loan_deductions_not_negative'), models.CheckConstraint(condition=models.Q(('other_deductions__gte', 0)), name='payout_other_deductions_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deducted', 'Deducted')], default='pending', max_length=20)),
                ('requested_on', models.DateField(default=django.utils.timezone.localdate)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loans', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.member')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.season')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='loan_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('delivery', 'Delivery'), ('loan', 'Loan'), ('payout', 'Payout'), ('deduction', 'Deduction')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.member')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.season')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('member', 'season', 'entry_type', 'reference'), name='unique_ledger_reference_per_member_season')],
            },
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_type', models.CharField(choices=[('cherry', 'Cherry'), ('parchment', 'Parchment'), ('green_bean', 'Green Bean')], max_length=20)),
                ('warehouse', models.CharField(max_length=120)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='core.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('season', 'stock_type', 'warehouse'), name='unique_stock_per_season_type_warehouse'), models.CheckConstraint(condition=models.Q(('quantity_kg__gte', 0)), name='inventory_quantity_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.CharField(choices=[('a', 'Grade A'), ('b', 'Grade B'), ('pb', 'Peaberry'), ('ungraded', 'Ungraded')], default='ungraded', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('collection_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.collectionpoint')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_deliveries', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.member')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.season')),
            ],
            options={
                'ordering': ['-delivery_date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('weight_kg__gt', 0)), name='delivery_weight_positive')],
            },
        ),
    ]
