# Generated by Django 6.0.6 on 2026-06-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('field_officer', 'Field Officer'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
