# Generated by Django 6.0.6 on 2026-07-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_secretary_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="collateral_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="eligible_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="loan",
            name="expected_production_kg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="interest_rate_percent",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("cherry_advance", "Cherry Advance"),
                    ("input_advance", "Farm Input Advance"),
                    ("development", "Development Loan"),
                    ("school_fees", "School Fees Loan"),
                    ("emergency", "Emergency Loan"),
                ],
                default="cherry_advance",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="proof_type",
            field=models.CharField(
                choices=[
                    ("delivery_history", "Recent Delivery Schedule"),
                    ("farm_acreage", "Farm Acreage"),
                    ("historical_yield", "Historical Yield"),
                    ("savings", "Savings or Shares"),
                ],
                default="delivery_history",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="rate_per_kg",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
        ),
        migrations.AddField(
            model_name="loan",
            name="savings_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="loan",
            name="term_months",
            field=models.PositiveIntegerField(default=6),
        ),
    ]
