# Generated by Django 6.0.6 on 2026-07-07 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_loan_collateral_details_loan_eligible_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="Default loan policy", max_length=120),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("applications_open", models.BooleanField(default=True)),
                (
                    "advance_rate_per_kg",
                    models.DecimalField(decimal_places=2, default=50, max_digits=8),
                ),
                (
                    "interest_rate_percent",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                (
                    "future_harvest_cap_percent",
                    models.DecimalField(decimal_places=2, default=60, max_digits=5),
                ),
                (
                    "max_unsecured_guarantor_loan",
                    models.DecimalField(
                        decimal_places=2, default=1000000, max_digits=12
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="loan",
            name="collateral_type",
            field=models.CharField(
                choices=[
                    ("future_harvest", "Future Harvest / Crop Lien"),
                    ("guarantor", "Member Guarantor"),
                ],
                default="future_harvest",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guaranteed_loans",
                to="core.member",
            ),
        ),
    ]
