# Generated by Django 6.0.6 on 2026-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fertilizerinventory_announcement_fertilizerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='payout_rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
