# Generated by Django 6.0.6 on 2026-07-11 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_season_payout_rate_per_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_reference', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('merchant_request_id', models.CharField(blank=True, max_length=120)),
                ('checkout_request_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=80)),
                ('result_code', models.CharField(blank=True, max_length=20)),
                ('result_description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_mpesa_transactions', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_transactions', to='core.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_transactions', to='core.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('manual', 'Manual'), ('payout_deduction', 'Payout Deduction')], default='mpesa', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='core.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to='core.member')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repayment', to='core.mpesatransaction')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='core_mpesat_checkou_04077c_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['member', 'status'], name='core_mpesat_member__9c6d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['loan', 'status'], name='core_mpesat_loan_id_46915d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='mpesa_transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='loan_repayment_amount_positive'),
        ),
    ]
