services:
  - type: web
    name: coffee-api
    runtime: python
    runtimeVersion: 3.11
    buildCommand: |
      cd backend/kaeve
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: cd backend/kaeve && gunicorn kaeve.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: USE_DATABASE_URL
        value: "True"
      - key: PYTHON_VERSION
        value: "3.11"
    autoDeploy: true

  - type: web
    name: coffee-frontend
    runtime: node
    runtimeVersion: 18
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        fromService:
          name: coffee-api
          property: url
    autoDeploy: true

  - type: pserv
    name: coffee-db
    ipAllowList: []
    plan: starter
    region: oregon
